In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
visitors = pd.read_csv('../data/parkvisitors2022.csv')

In [10]:
visitors

                           ParkName  Rank       Value PercentOfTotal
0          Great Smoky Mountains NP     1  12,937,633         14.59%
1                   Grand Canyon NP     2   4,732,101          5.34%
2                           Zion NP     3   4,692,417          5.29%
3                 Rocky Mountain NP     4   4,300,424          4.85%
4                         Acadia NP     5   3,970,260          4.48%
..                              ...   ...         ...            ...
58                   Isle Royale NP    59      25,454          0.03%
59             Lake Clark NP & PRES    60      18,187          0.02%
60                  Kobuk Valley NP    61      16,925          0.02%
61    Gates of the Arctic NP & PRES    62       9,457          0.01%
62  National Park of American Samoa    63       1,887          0.00%

[63 rows x 4 columns]

In [13]:
allvisitors = pd.read_csv('../data/allparkvisitors2022.csv')

In [14]:
allvisitors

                     ParkName  Rank       Value PercentOfTotal
0             Blue Ridge PKWY     1  15,711,004          5.04%
1             Golden Gate NRA     2  15,638,911          5.01%
2    Great Smoky Mountains NP     3  12,937,633          4.15%
3                 Gateway NRA     4   8,728,291          2.80%
4            Lincoln Memorial     5   7,825,397          2.51%
..                        ...   ...         ...            ...
382    Frederick Douglass NHS   383         211          0.00%
383        Alagnak Wild River   384         184          0.00%
384       Aniakchak NM & PRES   385         179          0.00%
385       John F. Kennedy NHS   386         100          0.00%
386         Rainbow Bridge NM   387          81          0.00%

[387 rows x 4 columns]